name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Linter
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      # Will add later, when there are tests
      # - name: Run Tests
      #   run: pnpm run test
